# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvHMEaqn7PHlQOowU3mzL5xZq90RG_Kx
"""

# ==========================================
# 1. Colab 環境設定與 Kaggle 資料下載
# ==========================================
import os
from google.colab import drive
import kagglehub

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# ⚠️ 請將這裡換成你存放 .pth 權重檔的雲端硬碟資料夾路徑！
# 例如：'/content/drive/MyDrive/Lassonde_Project'
PROJECT_DIR = '/content/drive/MyDrive/fairness and  bias'
os.chdir(PROJECT_DIR)
print(f"📁 目前工作目錄切換至: {os.getcwd()}")

# 2. 自動下載 Kaggle CelebA 資料集
print("⏳ 正在從 Kaggle 下載 CelebA 資料集...")
dataset_path = kagglehub.dataset_download("jessicali9530/celeba-dataset")
print(f"✅ 資料集下載完成！存放路徑: {dataset_path}")

# --- 💡 接下來請在這裡放入你的 prepare_dataloaders() 與 StandardResNet 模型定義 ---
# (跟你在本地端寫的程式碼一樣，確保 test_loader 和 model 準備就緒)

# ==========================================
# 補充步驟 1.5：定義神經網路模型與必備套件
# ==========================================
import torch
import torch.nn as nn
import torchvision.models as models

# 1. 定義你在本地端使用的 ResNet18 架構
class StandardResNet(nn.Module):
    def __init__(self, num_classes=2):
        super(StandardResNet, self).__init__()
        # 載入預訓練的 ResNet18
        self.model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        # 修改最後一層的全連接層以符合我們的分類數量 (金髮/非金髮 = 2)
        num_ftrs = self.model.fc.in_features
        self.model.fc = nn.Linear(num_ftrs, num_classes)

    def forward(self, x):
        return self.model(x)

print("✅ 模型架構 StandardResNet 定義完成！")

# ⚠️ 重要提醒：請確保你已經執行了資料讀取的程式碼！
# 你需要把你本地端用來產生 DataLoader 的程式碼貼過來執行，
# 確保環境中有 `test_loader` 這個變數，下一步的評估迴圈才抓得到圖片喔！

import os
import pandas as pd
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

class CelebADataset(Dataset):
    def __init__(self, root_dir, split='test', transform=None):
        self.root_dir = root_dir
        self.transform = transform

        # 處理 Kaggle 下載後可能產生的雙層資料夾結構
        img_dir = os.path.join(root_dir, 'img_align_celeba', 'img_align_celeba')
        if not os.path.exists(img_dir):
            img_dir = os.path.join(root_dir, 'img_align_celeba')

        attr_path = os.path.join(root_dir, 'list_attr_celeba.csv')
        eval_path = os.path.join(root_dir, 'list_eval_partition.csv')

        # 讀取屬性與分割檔
        attrs = pd.read_csv(attr_path)
        partitions = pd.read_csv(eval_path)

        # 合併資料並篩選測試集 (0: train, 1: val, 2: test)
        data = pd.merge(attrs, partitions, on='image_id')
        split_map = {'train': 0, 'val': 1, 'test': 2}
        data = data[data['partition'] == split_map[split]]

        self.image_ids = data['image_id'].values
        self.img_dir = img_dir

        # 將標籤與偏見屬性轉換為 0 與 1 (-1 轉為 0)
        self.targets = ((data['Blond_Hair'] == 1).astype(int)).values
        self.biases = ((data['Male'] == 1).astype(int)).values

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        img_name = os.path.join(self.img_dir, self.image_ids[idx])
        image = Image.open(img_name).convert('RGB')

        if self.transform:
            image = self.transform(image)

        target = self.targets[idx]
        bias = self.biases[idx]

        return image, target, bias

# 定義 ResNet 預設的影像轉換處理
transform_test = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# 建立 test_loader
test_dataset = CelebADataset(root_dir=dataset_path, split='test', transform=transform_test)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=2)

print(f"test_loader 建立完成。測試集包含 {len(test_dataset)} 張影像。")

# ==========================================
# 2. 模型推論與數據收集
# ==========================================
import torch
import pandas as pd
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"💻 目前使用的運算設備: {device}")

# 定義要評估的模型清單 (請確認檔名與你雲端硬碟中的一致)
# 這裡我們取 Best Worst-Group Acc 的權重來畫圖比較
models_to_evaluate = {
    'Baseline': 'best_wg_model_Baseline.pth',
    'Oversampling': 'best_wg_model_Oversampling.pth',
    'Undersampling': 'best_wg_model_Undersampling.pth',
    'Reweighting': 'best_wg_model_Reweighting.pth',
    'Focal Loss': 'best_wg_model_Focal Loss.pth'
}

results = []

for method_name, pth_name in models_to_evaluate.items():
    if not os.path.exists(pth_name):
        print(f"⚠️ 找不到檔案: {pth_name}，跳過此模型。")
        continue

    print(f"\n🔍 正在評估: {method_name}...")

    # 初始化模型
    model = StandardResNet(num_classes=2).to(device)

    # 讀取原本的權重檔
    original_state_dict = torch.load(pth_name, map_location=device, weights_only=True)

    # 修正 key 的名稱，對齊兩邊的變數命名
    new_state_dict = {}
    for k, v in original_state_dict.items():
        # 如果當初的變數名叫 backbone，把它換成 model
        if k.startswith('backbone.'):
            new_key = k.replace('backbone.', 'model.')
        # 如果當初最後一層叫做 fc 或 classifier，對應到 model.fc
        elif k.startswith('fc.'):
            new_key = k.replace('fc.', 'model.fc.')
        elif k.startswith('classifier.'):
            new_key = k.replace('classifier.', 'model.fc.')
        else:
            new_key = k

        new_state_dict[new_key] = v

    # 載入修正後的權重 (strict=False 允許忽略一些不影響的分類器名稱差異)
    model.load_state_dict(new_state_dict, strict=False)
    model.eval()

    all_preds, all_targets, all_biases = [], [], []

    # 假設 test_loader 已經透過你的 prepare_dataloaders 準備好
    with torch.no_grad():
        for images, targets, biases in tqdm(test_loader, desc="Testing"):
            images = images.to(device)
            logits = model(images)
            preds = torch.argmax(logits, dim=1)

            all_preds.append(preds.cpu())
            all_targets.append(targets.cpu())
            all_biases.append(biases.cpu())

    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    all_biases = torch.cat(all_biases)

    # --- 計算整體準確率 ---
    overall_acc = (all_preds == all_targets).float().mean().item()

    # --- 計算四大群體準確率 ---
    # 假設: Target=0(非金髮), Target=1(金髮) / Bias=0(女性), Bias=1(男性)
    groups_info = {
        'Non-Blonde Female': (0, 0),
        'Non-Blonde Male':   (0, 1),
        'Blonde Female':     (1, 0),
        'Blonde Male':       (1, 1)  # 最差群體 (Worst-Group)
    }

    group_metrics = {}
    for group_name, (t, b) in groups_info.items():
        mask = (all_targets == t) & (all_biases == b)
        acc = (all_preds[mask] == all_targets[mask]).float().mean().item() if mask.sum() > 0 else 0.0
        group_metrics[group_name] = acc

    worst_group_acc = min(group_metrics.values())

    # 儲存結果
    results.append({
        'Method': method_name,
        'Overall Accuracy': overall_acc,
        'Worst-Group Accuracy': worst_group_acc,
        **group_metrics  # 展開四大群體數據
    })

df_results = pd.DataFrame(results)
print("\n📊 數據收集完成！")
display(df_results)

# ==========================================
# 3. 繪製三張頂級學術圖表
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 設定整體字體與風格
sns.set_theme(style="whitegrid", context="talk")

# ---------------------------------------------------------
# 📊 圖表 1: 帕雷托前沿 (Pareto Trade-off Plot)
# ---------------------------------------------------------
plt.figure(figsize=(10, 8))
# 畫點
sns.scatterplot(
    data=df_results, x='Worst-Group Accuracy', y='Overall Accuracy',
    hue='Method', s=300, palette="Set1", edgecolor="black", alpha=0.9
)

# 加上標籤與理想區間
for i in range(df_results.shape[0]):
    plt.text(df_results['Worst-Group Accuracy'][i] + 0.005,
             df_results['Overall Accuracy'][i] + 0.005,
             df_results['Method'][i], fontsize=12, weight='bold')

plt.title('Trade-off: Overall vs. Worst-Group Accuracy', fontsize=18, pad=20)
plt.xlabel('Worst-Group Accuracy (Fairness ➔)', fontsize=14)
plt.ylabel('Overall Accuracy (Performance ➔)', fontsize=14)
# 畫出右上角的理想區域 (Target Zone)
plt.axvspan(0.85, 1.0, ymin=0.85, ymax=1.0, color='green', alpha=0.1, label='Ideal Zone')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('Plot1_Pareto_Tradeoff.png', dpi=300)
plt.show()

# ---------------------------------------------------------
# 📊 圖表 2: 四大群體準確率長條圖 (Group-wise Bar Chart)
# ---------------------------------------------------------
# 將資料轉為長格式 (Long format) 方便 Seaborn 繪製
df_melted = df_results.melt(
    id_vars=['Method'],
    value_vars=['Overall Accuracy', 'Non-Blonde Female', 'Non-Blonde Male', 'Blonde Female', 'Blonde Male'],
    var_name='Group', value_name='Accuracy'
)

plt.figure(figsize=(14, 8))
sns.barplot(
    data=df_melted, x='Method', y='Accuracy', hue='Group',
    palette=['#34495e', '#3498db', '#2ecc71', '#e74c3c', '#f1c40f'], edgecolor='black'
)
plt.title('Accuracy Breakdown by Demographic Groups', fontsize=18, pad=20)
plt.xlabel('De-biasing Method', fontsize=14)
plt.ylabel('Accuracy', fontsize=14)
plt.ylim(0, 1.05)
plt.axhline(y=df_results.loc[df_results['Method']=='Baseline', 'Blonde Male'].values[0],
            color='r', linestyle='--', alpha=0.6, label='Baseline Worst Group')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('Plot2_Group_Accuracy.png', dpi=300)
plt.show()

# ---------------------------------------------------------
# 📊 圖表 3: 準確率落差啞鈴圖 (Accuracy Gap / Variance Range Plot)
# ---------------------------------------------------------
plt.figure(figsize=(12, 6))

# 對每個 Method 畫一條線與兩個點
for index, row in df_results.iterrows():
    method = row['Method']
    # 找出該方法 四個群體 中的最高與最低準確率
    group_accs = [row['Non-Blonde Female'], row['Non-Blonde Male'], row['Blonde Female'], row['Blonde Male']]
    min_acc, max_acc = min(group_accs), max(group_accs)
    overall_acc = row['Overall Accuracy']

    # 畫出連接線 (Gap)
    plt.plot([min_acc, max_acc], [method, method], color='gray', linewidth=3, zorder=1)

    # 畫出最低點、最高點與整體準確率的點
    plt.scatter(min_acc, method, color='#e74c3c', s=200, zorder=2, label='Worst Group' if index==0 else "")
    plt.scatter(max_acc, method, color='#2ecc71', s=200, zorder=2, label='Best Group' if index==0 else "")
    plt.scatter(overall_acc, method, color='#34495e', s=150, zorder=2, marker='X', label='Overall Acc' if index==0 else "")

plt.title('Accuracy Gap Between Best and Worst Groups', fontsize=18, pad=20)
plt.xlabel('Accuracy', fontsize=14)
plt.xlim(0, 1.05)
plt.legend(loc='lower right')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('Plot3_Accuracy_Gap.png', dpi=300)
plt.show()